const macosSystemFonts = [
	'Academy Engraved LET',
	'Adelle Sans Devanagari',
	'AkayaKanadaka',
	'AkayaTelivigala',
	'Al Bayan',
	'Al Nile',
	'Al Tarikh',
	'American Typewriter',
	'Andale Mono',
	'Annai MN',
	'Apple Chancery',
	'Apple Braille',
	'Apple Color Emoji',
	'AppleGothic',
	'AppleMyungjo',
	'Apple SD Gothic Neo',
	'Apple Symbols',
	'Arial Black',
	'Arial',
	'Arial Hebrew',
	'Arial Hebrew Scholar',
	'Arial Narrow',
	'Arial Rounded MT Bold',
	'Arial Unicode MS',
	'Arima Koshi',
	'Arima Madurai',
	'Avenir',
	'Avenir Next',
	'Avenir Next Condensed',
	'Ayuthaya',
	'BM Dohyeon',
	'BM Hanna 11yrs Old',
	'BM Hanna Air',
	'BM Hanna Pro',
	'BM Jua',
	'BM Kirang Haerang',
	'BM Yeonsung',
	'Baghdad',
	'Bai Jamjuree',
	'Baloo 2',
	'Baloo Bhai 2',
	'Baloo Bhaijaan',
	'Baloo Bhaina 2',
	'Baloo Chettan 2',
	'Baloo Da 2',
	'Baloo Paaji 2',
	'Baloo Tamma 2',
	'Baloo Tammudu 2',
	'Baloo Thambi 2',
	'Bangla MN',
	'Bangla Sangam MN',
	'Baskerville',
	'Beirut',
	'Big Caslon',
	'Bodoni Ornaments',
	'Bodoni 72',
	'Bodoni 72 Oldstyle',
	'Bodoni 72 Smallcaps',
	'Bradley Hand',
	'Brush Script MT',
	'Cambay Devanagari',
	'Chakra Petch',
	'Chalkboard',
	'Chalkboard SE',
	'Chalkduster',
	'Charm',
	'Charmonman',
	'Charter',
	'Cochin',
	'Comic Sans MS',
	'Copperplate',
	'Corsiva Hebrew',
	'Courier New',
	'BiauKai',
	'Wawati SC',
	'Wawati TC',
	'DIN Alternate',
	'DIN Condensed',
	'Damascus',
	'DecoType Naskh',
	'Devanagari MT',
	'Devanagari Sangam MN',
	'Didot',
	'Diwan Kufi',
	'Mishafi',
	'Mishafi Gold',
	'Diwan Thuluth',
	'Euphemia UCAS',
	'Lantinghei TC',
	'Lantinghei SC',
	'Fahkwang',
	'Farah',
	'Farisi',
	'Futura',
	'GB18030 Bitmap',
	'Galvji',
	'Geeza Pro',
	'Geneva',
	'Georgia',
	'Gill Sans',
	'Gotu',
	'Grantha Sangam MN',
	'Gujarati MT',
	'Gujarati Sangam MN',
	'Gurmukhi MN',
	'Gurmukhi Sangam MN',
	'Hannotate SC',
	'Hannotate TC',
	'HanziPen SC',
	'HanziPen TC',
	'Helvetica',
	'Helvetica Neue',
	'Herculanum',
	'Hiragino Maru Gothic ProN',
	'Hiragino Mincho ProN',
	'Hiragino Sans',
	'Hiragino Sans CNS',
	'Hiragino Sans GB',
	'Hoefler Text',
	'Hubballi',
	'ITF Devanagari',
	'ITF Devanagari Marathi',
	'Impact',
	'InaiMathi',
	'HeadLineA',
	'PilGi',
	'GungSeo',
	'PCMyungjo',
	'Jaini',
	'Jaini Purva',
	'K2D',
	'Kailasa',
	'Kannada MN',
	'Kannada Sangam MN',
	'Katari',
	'Kavivanar',
	'Kefa',
	'Khmer MN',
	'Khmer Sangam MN',
	'Klee',
	'KoHo',
	'Kodchasan',
	'Kohinoor Bangla',
	'Kohinoor Devanagari',
	'Kohinoor Gujarati',
	'Kohinoor Telugu',
	'Kokonor',
	'Krub',
	'Krungthep',
	'KufiStandardGK',
	'Lahore Gurmukhi',
	'Lao MN',
	'Lao Sangam MN',
	'Lava Devanagari',
	'Lava Kannada',
	'Lava Telugu',
	'Apple LiGothic',
	'LiHei Pro',
	'LiSong Pro',
	'Apple LiSung',
	'Lucida Grande',
	'Luminari',
	'LingWai SC',
	'LingWai TC',
	'Maku',
	'Malayalam MN',
	'Malayalam Sangam MN',
	'Mali',
	'Marker Felt',
	'Menlo',
	'Microsoft Sans Serif',
	'Modak',
	'Monaco',
	'Gurmukhi MT',
	'Mshtakan',
	'Mukta',
	'Mukta Mahee',
	'Mukta Malar',
	'Mukta Vaani',
	'Muna',
	'Myanmar MN',
	'Myanmar Sangam MN',
	'Nadeem',
	'Nanum Brush Script',
	'Nanum Gothic',
	'Nanum Myeongjo',
	'Nanum Pen Script',
	'New Peninim MT',
	'Niramit',
	'Noteworthy',
	'Noto Nastaliq Urdu',
	'Noto Sans Kannada',
	'Noto Sans Myanmar',
	'Noto Sans Oriya',
	'Noto Serif Kannada',
	'Noto Serif Myanmar',
	'October Compressed Devanagari',
	'October Compressed Tamil',
	'October Condensed Devanagari',
	'October Condensed Tamil',
	'October Devanagari',
	'October Tamil',
	'Optima',
	'Oriya MN',
	'Oriya Sangam MN',
	'Osaka',
	'PSL Ornanong Pro',
	'PT Mono',
	'PT Sans',
	'PT Sans Caption',
	'PT Sans Narrow',
	'PT Serif',
	'PT Serif Caption',
	'Padyakke Expanded One',
	'Palatino',
	'Papyrus',
	'Party LET',
	'Phosphate',
	'PingFang HK',
	'PingFang SC',
	'PingFang TC',
	'Plantagenet Cherokee',
	'Raanana',
	'Rockwell',
	'Hei',
	'Kai',
	'Baoli SC',
	'Baoli TC',
	'STFangsong',
	'STHeiti',
	'Heiti SC',
	'Heiti TC',
	'STIXGeneral',
	'STIXIntegralsD',
	'STIXIntegralsSm',
	'STIXIntegralsUp',
	'STIXIntegralsUpD',
	'STIXIntegralsUpSm',
	'STIXNonUnicode',
	'STIXSizeFiveSym',
	'STIXSizeFourSym',
	'STIXSizeOneSym',
	'STIXSizeThreeSym',
	'STIXSizeTwoSym',
	'STIXVariants',
	'STKaiti',
	'Kaiti SC',
	'Kaiti TC',
	'Libian SC',
	'Libian TC',
	'STSong',
	'Songti SC',
	'Songti TC',
	'Xingkai SC',
	'Xingkai TC',
	'Yuanti SC',
	'Yuanti TC',
	'Sama Devanagari',
	'Sama Gujarati',
	'Sama Gurmukhi',
	'Sama Kannada',
	'Sama Malayalam',
	'Sama Tamil',
	'Sana',
	'Sarabun',
	'Sathu',
	'Savoye LET',
	'Shobhika',
	'Shree Devanagari 714',
	'SignPainter',
	'Silom',
	'SimSong',
	'Sinhala MN',
	'Sinhala Sangam MN',
	'Skia',
	'Snell Roundhand',
	'Srisakdi',
	'Sukhumvit Set',
	'Symbol',
	'Tahoma',
	'Tamil MN',
	'Tamil Sangam MN',
	'Telugu MN',
	'Telugu Sangam MN',
	'Thonburi',
	'Times New Roman',
	'Tiro Bangla',
	'Tiro Devanagari Hindi',
	'Tiro Devanagari Marathi',
	'Tiro Devanagari Sanskrit',
	'Tiro Gurmukhi',
	'Tiro Kannada',
	'Tiro Tamil',
	'Tiro Telugu',
	'Toppan Bunkyu Gothic',
	'Toppan Bunkyu Midashi Gothic',
	'Toppan Bunkyu Midashi Mincho',
	'Toppan Bunkyu Mincho',
	'Trattatello',
	'Trebuchet MS',
	'Tsukushi A Round Gothic',
	'Tsukushi B Round Gothic',
	'Verdana',
	'Waseem',
	'Webdings',
	'Weibei SC',
	'Weibei TC',
	'Wingdings',
	'Wingdings 2',
	'Wingdings 3',
	'YuGothic',
	'YuKyokasho',
	'YuKyokasho Yoko',
	'YuMincho',
	'YuMincho +36p Kana',
	'Yuppy SC',
	'Yuppy TC',
	'Zapf Dingbats',
	'Zapfino',
];

export default macosSystemFonts;
